# Generated by Django 3.2.21 on 2024-01-03 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_questions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
