# Generated by Django 3.2.21 on 2024-01-06 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20240103_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
