# Generated by Django 3.2.21 on 2024-01-07 23:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
