# Generated by Django 3.2.21 on 2024-01-08 08:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_questions_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
