# Generated by Django 5.0.1 on 2024-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_comment_likes_questions_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='likes',
        ),
        migrations.AddField(
            model_name='questions',
            name='ip_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
